jaffle_shop:
  outputs:
    dev:
      type: duckdb
      repository: https://github.com/Akshaidevopscc/jaffle_shop
    prod:
      type: duckdb
      repository: https://github.com/Akshaidevopscc/jaffle_shop
  target: dev
